services:
  - type: web
    name: llm-group-discussion
    env: python
    buildCommand: "pip install -r requirements.txt && cd web && npm install && npm run build && cd .."
    startCommand: "python web_api.py"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: NODE_VERSION
        value: 18
    autoDeploy: true